---
# tasks file for apache



- name: Install Apache
  yum:
    name: httpd
    state: latest

- name: copy httpd.conf template
  template: 
    src: httpd.conf
    dest: /tmp
  notify: httpd


- name: Enable Apache
  service: 
    name: httpd
    state: started
    enabled: yes


