---
- hosts: all
  become: true
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
    timesync_ntp_servers:
      - hostname: pool.ntp.org

  roles:
  - rhel-system-roles.selinux
  - rhel-system-roles.timesync
