---

- hosts: all
  #Specify the SSH User
  remote_user: centos
  #To sudo or not to sudo
  become: true

  tasks:
  - name: Just running stat on a file to register output

    file:
      path: /etc/ansible/hosts
      state: file
    register: file_stat
  - name: Debug output
    debug:
      msg: "{{ file_stat }}"
