---

- hosts: all
  remote_user: root

  tasks:
  - name: Just running stat on a file to register output

    file:
      path: /etc/ansible/inventory
      state: file
    register: file_stat
  - name: Debug output
    debug:
      msg: {{ file_stat }}
